running: local
domain: http://localhost:8080
S3domain: http://localhost:3000


spring:
  profiles:
    include: common
    active: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
        highlight_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail_username}
    password: ${gmail_password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 759272438227-e8o3ofaekd3d6svf6i8tinfp09pbdtap.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.typedescriptor.sql.BasicBinder: trace

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 1800000
  refresh-token-expiration-minutes: 604800000

mail:
  address:
    admin: ${admin_mail}